SkydivePortal/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json.Linq;
using SkydivePortal.Data;
using SkydivePortal.Models;
using SkydivePortal.Models.ProfileViewModels;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;

namespace SkydivePortal.Controllers
{
    public class ProfileController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ProfileController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var profileView = new ProfileViewModel();
            var user = await _userManager.GetUserAsync(User);
            if(user != null)
            {
                int newJumpNumber = 0;
                profileView.ApplicationUser = user;
                profileView.UserJumps = await _context.UserJumps.Where(u => u.ApplicationUserId == user.Id).OrderByDescending(u => u.Number).AsNoTracking().ToListAsync();
                foreach(var userJump in profileView.UserJumps)
                {
                    if(userJump.Number > newJumpNumber)
                    {
                        newJumpNumber = userJump.Number;
                    }
                }
                newJumpNumber++;
                profileView.UserJump = new UserJump()
                {
                    Number = newJumpNumber,
                    Date = DateTime.Now
                };
                return View(profileView);
            }

            ViewData["loggedIn"] = "no";

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddJump ([Bind("Number,Date,Height,Parachute,Plane,Note,Video")] UserJump userJump)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var user = await _userManager.GetUserAsync(User);
                    userJump.ApplicationUser = user;

                    if(user != null)
                    {
                        List<UserJump> jumpList = new List<UserJump>();
                        jumpList = await _context.UserJumps.Where(u => u.ApplicationUserId == user.Id).OrderBy(u => u.Number).ToListAsync();

                        if(jumpList.Exists(j => j.Number == userJump.Number))
                        {
                            int currentNumber = userJump.Number;
                            bool reachedItem = false;

                            foreach(var item in jumpList)
                            {
                                if (item.Number == currentNumber)
                                {
                                    reachedItem = true;
                                    item.Number = currentNumber + 1;
                                    _context.Update(item);
                                    currentNumber++;
                                }else if (reachedItem == true)
                                {
                                    break;
                                }
                                
                            }
                            _context.Add(userJump);
                            await _context.SaveChangesAsync();
                        }
                        else
                        {
                            _context.Add(userJump);
                            await _context.SaveChangesAsync();
                        }

                        
                    }    
                }
            }
            catch (DbUpdateException /* ex */)
            {
                //Log the error (uncomment ex variable name and write a log.
                ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists " +
                    "see your system administrator.");
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> RemoveJump(int id)
        {
            var user = await _userManager.GetUserAsync(User);

            if (user != null)
            {
                UserJump toDelete = await _context.UserJumps.SingleOrDefaultAsync(u => u.ApplicationUserId == user.Id && u.Id == id);
                if(toDelete != null)
                {
                    int currentNumber = toDelete.Number;
                    _context.Remove(toDelete);

                    List<UserJump> jumpList = new List<UserJump>();
                    jumpList = await _context.UserJumps.Where(u => u.ApplicationUserId == user.Id).OrderBy(u => u.Number).ToListAsync();

                    currentNumber++;
                    bool reachedItem = false;

                    foreach (var item in jumpList)
                    {
                        if (item.Number == currentNumber)
                        {
                            reachedItem = true;
                            item.Number = currentNumber - 1;
                            _context.Update(item);
                            currentNumber++;
                        }
                        else if (reachedItem == true)
                        {
                            break;
                        }

                    }

                    await _context.SaveChangesAsync();
                }

            }

            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<IActionResult> EditJump([Bind("Id,Number,Date,Height,Parachute,Plane,Note,Video")] UserJump userJump)
        {
            var user = await _userManager.GetUserAsync(User);

            if (user != null)
            {
                try
                {
                    var toEdit = await _context.UserJumps.SingleOrDefaultAsync(u => u.Id == userJump.Id);
                    if (toEdit != null && ModelState.IsValid)
                    {
                        if (toEdit.ApplicationUserId == user.Id)
                        {
                            if (toEdit.Number != userJump.Number)
                            {
                                int currentNumber = toEdit.Number;

                                List<UserJump> jumpList = new List<UserJump>();
                                jumpList = await _context.UserJumps.Where(u => u.ApplicationUserId == user.Id).OrderBy(u => u.Number).ToListAsync();

                                currentNumber++;
                                bool reachedItem = false;

                                foreach (var item in jumpList)
                                {
                                    if (item.Number == currentNumber)
                                    {
                                        reachedItem = true;
                                        item.Number--;
                                        _context.Update(item);
                                        currentNumber++;
                                    }
                                    else if (reachedItem == true)
                                    {
                                        break;
                                    }

                                }
                                currentNumber = userJump.Number;
                                reachedItem = false;

                                foreach (var item in jumpList)
                                {
                                    if (item.Id == toEdit.Id)
                                    {
                                        continue;
                                    }
                                    if (item.Number == currentNumber)
                                    {
                                        reachedItem = true;
                                        item.Number++;
                                        _context.Update(item);
                                        currentNumber++;
                                    }
                                    else if (reachedItem == true)
                                    {
                                        break;
                                    }

                                }

                            }
                            toEdit.Number = userJump.Number;
                            toEdit.Date = userJump.Date;
                            toEdit.Height = userJump.Height;
                            toEdit.Parachute = userJump.Parachute;
                            toEdit.Plane = userJump.Plane;
                            toEdit.Note = userJump.Note;
                            toEdit.Video = userJump.Video;

                            _context.Update(toEdit);
                            await _context.SaveChangesAsync();
                        }
                    }
                }
                catch (DbUpdateException /* ex */)
                {
                    //Log the error (uncomment ex variable name and write a log.
                    ModelState.AddModelError("", "Unable to save changes. " +
                        "Try again, and if the problem persists " +
                        "see your system administrator.");
                }
            }


            return RedirectToAction(nameof(Index));
        }
    }
}

SkydivePortal/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json.Linq;
using SkydivePortal.Data;
using SkydivePortal.Models;
using SkydivePortal.Models.UsersViewModels;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;

namespace SkydivePortal.Controllers
{
    public class UsersController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public UsersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.Include(u => u.Parachute).Include(u => u.Region).ThenInclude(r => r.Country).ToListAsync();
            var model = new List<UserViewModel>();
            foreach(var user in users)
            {
                var modelItem = new UserViewModel()
                {
                    ApplicationUser = user,
                    ApplicationUserRoles = await _context.ApplicationUserRoles.Where(ar => ar.ApplicationUserId == user.Id).Include(ar => ar.ApplicationRole).ThenInclude(a => a.Dropzone).ToListAsync()
                };
                model.Add(modelItem);
            }
            return View("Index", model);
        }
    }
}

SkydivePortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SkydivePortal</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/home.css" />
        <link rel="stylesheet" href="~/css/jumplog.css" />
        <link rel="stylesheet" href="~/css/dropzones.css" />
        <link rel="stylesheet" href="~/css/users.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/home.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/jumplog.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/dropzones.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/users.css" asp-append-version="true" />
    </environment>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/autosize.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/autosize.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

</head>
<body>
    <nav class="navbar navbar-inverse navbar-default">
        <div class="container" id="navbar-container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" id="toggle-button" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img class="img-responsive" src="~/images/skydiver-web.png">
            </div>
            <div class="navbar-collapse collapse">
                <img class="img-responsive" src="~/images/napis.png">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index"><span class="glyphicon glyphicon-home"></span> Home</a></li>
                    <li><a asp-area="" asp-controller="Profile" asp-action="Index"><span class="glyphicon glyphicon-cloud"></span> Jump Log</a></li>
                    <li><a asp-area="" asp-controller="Dropzone" asp-action="Index"><span class="glyphicon glyphicon-plane"></span> Dropzones</a></li>
                    <li><a asp-area="" asp-controller="Users" asp-action="Index"><span class="glyphicon glyphicon-user"></span> Users</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr class="hr-custom" />
        <footer>
            <p>&copy; 2018 - SkydivePortal</p>
        </footer>
    </div>



    @RenderSection("Scripts", required: false)
</body>
</html>